version: '3.9'

services:
  postgres:
    image: postgres:alpine
    volumes:
      - feed-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-go_db}"
      DB_SSLMODE: "${DB_SSLMODE:-disable}"
      API_SECRET: "${API_SECRET:-secret}"
      TOKEN_HOUR_LIFESPAN: "${TOKEN_HOUR_LIFESPAN:-1}"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-go_db}"

volumes:
  feed-data:
